FROM python:3.10-slim

# Install uv
COPY --from=ghcr.io/astral-sh/uv:0.9.16 /uv /uvx /bin/
ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
# ENV UV_SYSTEM_PYTHON=1

# # Install ffmpeg
# RUN --mount=type=bind,source=./models/ffmpeg,target=/app/models/ffmpeg \
#     cp -r /app/models/ffmpeg/dist/* /usr/local/ && \
#     ldconfig

# Copy models
COPY models/openbmb/VoxCPM1.5 /app/models/openbmb/VoxCPM1.5
COPY models/iic/speech_zipenhancer_ans_multiloss_16k_base /app/models/iic/speech_zipenhancer_ans_multiloss_16k_base
COPY models/iic/SenseVoiceSmall /app/models/iic/SenseVoiceSmall

COPY run.py /app/run.py

# Install dependencies
RUN --mount=type=cache,target=/root/.cache/uv \
    uv venv -p 3.10 && uv pip install -U pip

# Add venv python to PATH
ENV PATH="/app/.venv/bin:$PATH"

RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=./requirements-pypi.txt,target=/requirements-pypi.txt \
    uv pip install -r /requirements-pypi.txt

COPY dist/server /app/server

WORKDIR /app
EXPOSE 3000
ENV HF_HUB_OFFLINE=1

CMD python3 run.py
